######################################################################
# Automatically generated by qmake (3.0) ?? 2? 16 12:26:40 2015
######################################################################

TEMPLATE = app
TARGET = Test
INCLUDEPATH += .

# Input
SOURCES += main.cpp
